### ISSUE TITLE
Distributed zzz.exe is triggering virus warnings

### ISSUE THREAD

**Issue by Pinchie** [myst6re/qt-zzz#1]
Wanted to run it, but Windows Defender was vehemently against it.
Popped the zzz.exe file from the zip up to virustotal.com and it came up with four detections:

![image](https://user-images.githubusercontent.com/8608862/64263087-70f77e00-cf72-11e9-84f8-770d5b398e28.png)

I'm _assuming_ they're false positives, but I'm not really able to check

**Comment by jerome-arzel** [comment]
The executable file provided here was compressed by upx, it is not really needed, and maybe it causes this false-positive result.

**Comment by myst6re** [comment]
The executable file provided here was compressed by upx, it is not really needed, and maybe it causes this false-positive result.

**Comment by myst6re** [comment]
Can you try with the [new release](https://github.com/myst6re/qt-zzz/releases/tag/v0.1.0)?

**Comment by Pinchie** [comment]
Passed with no detection - thank you :)
