### ISSUE TITLE
Fails to extract most of the time

### ISSUE THREAD

**Issue by pitrako** [myst6re/qt-zzz#2]
At least for me, It's necessary to run with admin rights?

**Comment by myst6re** [comment]
It depends on your output directory. If you try to extract files into Program Files subdirectories, you can't do that without admin rights. If you try in your user folder, you shouldn't have any trouble.

**Comment by pitrako** [comment]
It gives me error "0xc0000142" most of the time, I'm not in program files, sometimes It extracts correctly. I use "zzz -e main.zzz main" inside the zzz.exe program folder with the main.zzz inside too.

**Comment by myst6re** [comment]
There is a new release, could you try it?

**Comment by IFireflyl** [comment]
The program doesn't even run for me. I'd say maybe I'm doing something wrong, but it seems like all I should have to do is extract the files and run the executable. The vcredist executable says "Another version of this product is already installed", so I doubt I'm doing something wrong. This is with version 0.1.0.

Edit: I tried the original version (0.0.1) and it at least attempts to run. It ends up crashing with the error "The application was unable to start correctly (0xc0000142). Click OK to close the application."

**Comment by pitrako** [comment]
I use "zzz extract main.zzz main" and "zzz pack main.zzz main", now It always works. Another question..., where are located the prerendered backgrounds of the game, in the main.zzz or the other.zzz?, because I don't find it in the texture folder.

**Comment by myst6re** [comment]
In field.fs/fl/fi archives. My software Deling can't open Remaster version yet, but it will soon.
Please ask this kind of questions in [the Qhimm forum](http://forums.qhimm.com).
